### ISSUE TITLE
Crash on hovering cursor on specific items

### ISSUE THREAD

**Issue by ChromaPIE** [cubicgraphics/dronecraft_2#1]
**Describe the bug**
Described as title. Crash report: https://www.toptal.com/developers/hastebin/ekatamozuw.rb
Additionally several items from the mod shows missing purple-black textures. Might caused by mods like Rubidium (Sodium Forge fork) but I'm not so sure.

**Comment by cubicgraphics** [comment]
The mod is in early alpha so i have just not got around to giving a few of the items textures yet,
As for the crash... looks like something to do with ProjectE. It seems to be trying to cast the PCB capability to an IPedestalItem and i don't know why it would be trying to do that. I don't think it is anything i can fix on my end... Well thanks for the bug report but i recommend not using my mod in a modpack/lots of mods yet as it is incomplete/possibly unstable and unfortunately i am currently very busy and cannot update it.

**Comment by ChromaPIE** [comment]
That's fine. It's just to make it known.
